# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 706df0905e6ce30144edb0bd1e66f62662006b59f5109aa3d2401d18f8a2f299440a17cebfec9a5b21a915373dba7279509296e13ca1f9903de10589ec93388e

test:
  secret_key_base: d54842daf96cf826d6f8b89cb302bef7a8ad238d44ebe8c03b783541da58e7ef18fa6f6aec31f779b70a2bda0e520fb58ffed09d3951b46184877afcd72dadfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
